language: android
jdk: oraclejdk8
os: linux

android:
    components:
    - platform-tools
    - tools
    - build-tools-25.0.0
    - build-tools-23.0.3
    - android-25
    - android-19

cache:
    directories:
        - $HOME/.gradle

install:
    - chmod +x gradlew
    - git clone https://github.com/MusalaSoft/atmosphere-commons.git
    - git clone https://github.com/MusalaSoft/atmosphere-agent-device-lib.git
    - git clone https://github.com/MusalaSoft/atmosphere-server-agent-lib.git
    - git clone https://github.com/MusalaSoft/atmosphere-ime.git
    - git clone https://github.com/MusalaSoft/atmosphere-service.git
    - git clone https://github.com/MusalaSoft/atmosphere-uiautomator-bridge.git
    - chmod +x travis-scripts/branch-checkout.sh
    - cd atmosphere-commons && ../travis-scripts/branch-checkout.sh
    - ./gradlew build publishToMavenLocal && cd ..
    - cd atmosphere-agent-device-lib && ../travis-scripts/branch-checkout.sh
    - ./gradlew build publishToMavenLocal && cd ..
    - cd atmosphere-server-agent-lib && ../travis-scripts/branch-checkout.sh
    - ./gradlew build publishToMavenLocal && cd ..
    - cd atmosphere-ime && ../travis-scripts/branch-checkout.sh
    - ./gradlew build publishToMavenLocal && cd ..
    - cd atmosphere-service && ../travis-scripts/branch-checkout.sh
    - ./gradlew build publishToMavenLocal && cd ..
    - cd atmosphere-uiautomator-bridge && ../travis-scripts/branch-checkout.sh
    - ./gradlew build publishToMavenLocal && cd ..

script:
    - ./gradlew build publishToMavenLocal
