language: android
jdk: oraclejdk7
os: 
    - linux

notifications:
  email:
    recipients:
        - atmosphere@musala.com

android:
    components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-19
    - extr

cache:
    directories:
        - $HOME/.gradle

before_script:
    - chmod +x gradlew

script:
    - ./gradlew build
